# Generated by Django 6.1 on 2026-08-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crowd_status', models.CharField(max_length=50)),
                ('waiting_time', models.CharField(max_length=50)),
                ('best_time_to_visit', models.CharField(max_length=100)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='places.place')),
            ],
        ),
    ]
