# Generated by Django 6.1 on 2026-08-23 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_occupancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupancy',
            options={'verbose_name_plural': 'Occupancies'},
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('parking_status', models.CharField(max_length=50)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='places.place')),
            ],
            options={
                'verbose_name_plural': 'Parking',
            },
        ),
    ]
