# Generated by Django 6.1 on 2026-08-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_district_place_latitude_place_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='source_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
