# Generated by Django 6.1 on 2026-08-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_place_source_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
