# Generated by Django 6.1 on 2026-08-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_alternate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('service_type', models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('parking', 'Parking'), ('fuel', 'Fuel Station'), ('hospital', 'Hospital'), ('bank', 'Bank'), ('cafe', 'Cafe'), ('grocery', 'Grocery'), ('pharmacy', 'Pharmacy'), ('transport', 'Transport')], max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
