# Generated by Django 6.1 on 2026-09-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_nearbyservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplan',
            name='trip_name',
        ),
        migrations.AddField(
            model_name='tripplan',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='route_details',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='start_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='stops',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripplan',
            name='total_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='total_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
