# Generated by Django 6.1 on 2026-09-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_remove_tripplan_trip_name_tripplan_destination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parking',
            options={},
        ),
        migrations.RemoveField(
            model_name='parking',
            name='available_slots',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='parking_status',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='total_slots',
        ),
    ]
