# Generated by Django 6.1 on 2026-09-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_parking_options_remove_parking_available_slots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parking',
            options={'verbose_name_plural': 'Parking'},
        ),
        migrations.AddField(
            model_name='parking',
            name='available_slots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='parking_status',
            field=models.CharField(blank=True, default='Not updated', max_length=50),
        ),
        migrations.AddField(
            model_name='parking',
            name='total_slots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
