# Generated by Django 6.1 on 2026-09-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_parking_options_parking_available_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
