# Generated by Django 6.1 on 2026-09-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
