# Generated by Django 6.1 on 2026-10-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_place_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='place',
            name='closing_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='opening_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
